### ISSUE TITLE
Multiple hue masks overlapping eachother

### ISSUE THREAD

**Issue by namng-uwu** [seth814/Semantic-Shapes#11]
Hi, I was trying to create hue masks for multi-class segmentation for U-Net using Image Masks and Augmentation.ipynb in your repo but my labels ended up overlapping each other like this and my road label was supposed to be behind of all labels. Any idea to bring the road label to the back of all labels? Thanks

![Screenshot (50)](https://user-images.githubusercontent.com/55870032/99387944-628f4b00-2907-11eb-9b8c-80aceadbb8ca.png)

**Comment by seth814** [comment]
Are you getting the correct predictions and it's just drawing the boxes incorrectly? I never really tested this with overlapping bounding boxes. I'd recommend using a different repository.
